name: mgkarateclub

channels:
- conda-forge

dependencies:
# dev environment
  - python=3.8
  - black
  - conda-forge::pre-commit
  - setuptools
  - metagraph::metagraph-dev

# metagraph-karateclub dependencies
  - conda-forge::karateclub

