name: mg

channels:
- conda-forge

dependencies:
# dev environment
  - python=3.8
  - coverage
  - pytest
  - pytest-cov
  - black
  - conda-forge::pre-commit
  - setuptools
  - metagraph::metagraph

# metagraph-karateclub dependencies
  - conda-forge::karateclub

