name: mg

channels:
- conda-forge
- metagraph/label/dev

dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black
  - pre-commit
  - setuptools

# metagraph-karateclub dependencies
  - karateclub
  - metagraph
