package:
   name: metagraph_karateclub
   version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
   path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: {{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python >=3.7
  run:
    - python >=3.7
    - karateclub
    - metagraph

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --cov-report term-missing --cov=metagraph_karateclub --pyargs metagraph.tests

about:
  home: https://github.com/metagraph-dev/metagraph-karateclub
  license: Apache2
  license_file: LICENSE
  summary: Metagraph plugin for karateclub
